// 文案统一管理

export const textConfig = {
  professional: {
    welcome: "欢迎使用 TRIZ 发明问题解决理论工具",
    questionTitle: "问题描述",
    questionPlaceholder: "请详细描述您遇到的技术问题",
    questionExample: "例如：如何提高产品性能同时降低成本",
    nextButton: "下一步",
    conflictsTitle: "矛盾分析矩阵",
    conflictEmpty: "暂无矛盾数据",
    conflictExpand: "展开",
    conflictCollapse: "收起",
    generateButton: "生成解决方案",
    solutionTitle: "创新解决方案",
    saveButton: "保存方案",
    deleteButton: "删除",
    loading: "AI 分析中...",
    complete: "生成完成",
    saveSuccess: "保存成功",
    deleteConfirm: "确定要删除吗？",
    versionSwitchTitle: "选择你的使用方式",
    versionProfessional: "专业版",
    versionLifestyle: "生活版",
    versionProfessionalDesc: "专注技术问题",
    versionLifestyleDesc: "温柔讲解原理",
    emptyGrid: "暂无已保存的九宫格",
    relatedSolutions: "关联的解决方案",
    principleName: "发明原理",
    principleNumber: "原理编号",
    application: "应用分析",
    implementation: "实施要点",
    cases: "相关案例"
  },
  lifestyle: {
    welcome: "帮你理清那些复杂纠结，找到创新思路",
    questionTitle: "说说你的纠结",
    questionPlaceholder: "把你遇到的问题，用你自己的话说出来吧",
    questionExample: "例如：想减肥但又不想戒美食怎么办？或者想省钱又不想降低生活质量",
    nextButton: "继续",
    conflictsTitle: "你的纠结清单",
    conflictEmpty: "这里还空着呢，快去填写问卷吧",
    conflictExpand: "看看怎么办",
    conflictCollapse: "先收起来吧",
    generateButton: "帮我想想办法",
    solutionTitle: "破解方案",
    saveButton: "保存这个想法",
    deleteButton: "不要这个了",
    loading: "🤔 正在帮你思考...",
    complete: "✨ 想到了！",
    saveSuccess: "✅ 保存成功啦！",
    deleteConfirm: "真的不要这个了吗？",
    versionSwitchTitle: "选择你的使用方式",
    versionProfessional: "专业版",
    versionLifestyle: "生活版",
    versionProfessionalDesc: "专注技术问题",
    versionLifestyleDesc: "温柔讲解原理",
    emptyGrid: "📭 这里还空着呢，快去创建你的第一个纠结清单吧",
    relatedSolutions: "💡 关联的方案",
    principleName: "🔧 发明原理",
    principleNumber: "📊 原理编号",
    application: "📖 应用分析",
    implementation: "🛠️ 实施要点",
    cases: "💼 相关案例"
  }
};

export default textConfig;
